In [1]:
import numpy as np
a=np.arange(10).reshape(5,2)
b=np.array([[1,2,3,4],[6,7,8,9]])
print(a)
print(b)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.dtype)
print(type(a))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 2 3 4]
 [6 7 8 9]]
2
(5, 2)
8
10
int64
<class 'numpy.ndarray'>


In [11]:
#creating of arrays
import numpy as np
a=np.array([(1,2,5,6),(8,6,4,2)])
print(a)
b=np.zeros([3,4])
print(b)
c=np.ones([2,4])
print(c)
print(np.arange(10,50,7))
np.arange(10000).reshape(100,100)

[[1 2 5 6]
 [8 6 4 2]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 17 24 31 38 45]


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])